### ISSUE TITLE
建议增加readme.md多账户使用  want_watch的说明

### ISSUE THREAD

**Issue by bafangseo** [arcturus-script/bilibili#11]
一直报错，回来看了下issues才明白
多账户一定要添加want_watch
0,0或者1,0
0,0是测试成功了
但是现在写1就会报错，不知道哪里的问题

**Comment by ICE99125** [comment]
写的比较粗糙，没考虑一些问题，多账户的话需要两个都写，比如 1,1/0,0/0,1/1,0

**Comment by ICE99125** [comment]
重构了一下，配置信息就在 config.py 里写了，不需要环境变量了
