### ISSUE TITLE
pushplus整点推送失败

### ISSUE THREAD

**Issue by beggerlove** [arcturus-script/bilibili#15]
Starting new HTTP connection (1): www.pushplus.plus:80

推送时出现错误, 原因: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

Response RequestId:286c10da-a8e5-4dbe-9c72-cef50ef43872 RetMsg:null

END RequestId:286c10da-a8e5-4dbe-9c72-cef50ef43872

Report RequestId:286c10da-a8e5-4dbe-9c72-cef50ef43872 Duration:6294ms Memory:128MB MemUsage:17.051018MB

![Screenshot_2022-03-04-00-27-31-53_fab32b241c9ab51b0e057c943b753947.jpg](https://user-images.githubusercontent.com/65286493/156607851-d1b39960-fa2a-41ce-aa7c-eaff817d5200.jpg)

**Comment by ICE99125** [comment]
不懂😭，会不会是pushplus那边的问题，你明天再看看是不是复现了

**Comment by beggerlove** [comment]
好嘞

**Comment by beggerlove** [comment]
> 不懂😭，会不会是pushplus那边的问题，你明天再看看是不是复现了

应该是零点调用接口人过多的问题 其他时间段没问题
