### ISSUE TITLE
腾讯云函数下个月开始收费了，能移植到阿里云上面么

### ISSUE THREAD

**Issue by u2shana** [arcturus-script/bilibili#22]
目前的版本我直接在阿里云函数运行会出错

**Comment by ICE99125** [comment]
![image](https://user-images.githubusercontent.com/65435402/165993143-8b84cf16-002c-47c0-b6fb-f8d356cc4b90.png)
这里改一下，我运行没问题

**Comment by u2shana** [comment]
> ![image](https://user-images.githubusercontent.com/65435402/165993143-8b84cf16-002c-47c0-b6fb-f8d356cc4b90.png) 这里改一下，我运行没问题

我改了的,完完整整从隔壁复制过来,结果运行直接超时报错

**Comment by u2shana** [comment]
好吧,我找到原因了,不知道为什么这个新创建的服务默认关闭外网访问

**Comment by Re1uy** [comment]
函数入口是改成index.main吗，为什么我这么改还是报错
<img width="514" alt="image" src="https://user-images.githubusercontent.com/52073159/169548277-8ad7107f-eb6c-4111-9a6d-c035e3593b44.png">

**Comment by ICE99125** [comment]
是不是没有index.py文件啊

**Comment by ICE99125** [comment]
> 函数入口是改成index.main吗，为什么我这么改还是报错 <img alt="image" width="514" src="https://user-images.githubusercontent.com/52073159/169548277-8ad7107f-eb6c-4111-9a6d-c035e3593b44.png">

是不是没有index.py文件啊

**Comment by Re1uy** [comment]
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/52073159/169550473-9247ee20-c9e1-4fc2-b2bc-d1439d91dd07.png">
有的

**Comment by u2shana** [comment]
> <img alt="image" width="1174" src="https://user-images.githubusercontent.com/52073159/169550473-9247ee20-c9e1-4fc2-b2bc-d1439d91dd07.png">
> 
> 有的
你这个函数入口不对,多了个biliXXX的文件夹

**Comment by Re1uy** [comment]
哦哦,成功了,谢谢大佬
