### ISSUE TITLE
push 推送报错

### ISSUE THREAD

**Issue by magickzl** [arcturus-script/bilibili#7]
{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 386, in main\n    return start()\n  File \"/var/user/index.py\", line 372, in start\n    p.push_message('BiliBili', '\\n'.join(msg))\n  File \"/var/user/push.py\", line 108, in push_message\n    print(f\"发送消息失败: {rep.msg}\")\nAttributeError: 'dict' object has no attribute 'msg'","statusCode":430}

**Comment by ICE99125** [comment]
修改了
