### ISSUE TITLE
多账号登录错误

### ISSUE THREAD

**Issue by 2186056836** [arcturus-script/bilibili#8]
函数服务帮助文档
函数管理
触发管理
监控信息
日志查询
并发配额
部署日志
函数管理
版本：$LATEST
操作
函数配置函数代码层管理监控信息日志查询
提交方法	
在线编辑
执行方法	
index.main
运行环境	
Python3.6
Python3.6 开发教程
下载
1
部署测试
测试事件	
Hello World事件模板
{
  "key1": "test value 1",
  "key2": "test value 2"
}
执行摘要测试失败
请求ID	
906e86d5-3720-4e60-aed2-9e8b572fbd4f
运行时间	
6,051ms
运行内存	
16.71MB
返回结果

Text
没有日志输出

执行日志
START RequestId:906e86d5-3720-4e60-aed2-9e8b572fbd4f

Starting new HTTP connection (1): api.bilibili.com:80

http://api.bilibili.com:80 "GET /x/space/myinfo HTTP/1.1" 200 None

{'status': True, 'userInfo': {'name': '被打断脚的孩纸', 'level': 2, 'coins': 1, 'level_exp': '205/1500', 'silence': 0}}

等级：lv2<br/>硬币：1<br/>经验：205/1500<br/>

正在观看视频...

Starting new HTTPS connection (1): api.bilibili.com:443

https://api.bilibili.com:443 "GET /x/web-interface/view?bvid=BV1if4y1g7Qp HTTP/1.1" 200 None

Starting new HTTPS connection (1): api.bilibili.com:443

https://api.bilibili.com:443 "POST /x/click-interface/click/web/h5 HTTP/1.1" 200 32

Starting new HTTPS connection (1): api.bilibili.com:443

https://api.bilibili.com:443 "POST /x/click-interface/web/heartbeat HTTP/1.1" 200 32

Starting new HTTPS connection (1): api.bilibili.com:443

https://api.bilibili.com:443 "POST /x/click-interface/web/heartbeat HTTP/1.1" 200 32

观看视频成功🎉🎉

Starting new HTTPS connection (1): api.bilibili.com:443

https://api.bilibili.com:443 "GET /x/web-interface/popular?ps=50&pn=1 HTTP/1.1" 200 None

获取 50 个视频成功🎉🎉

今日欲投0个硬币

投币完成,正在退出

正在分享视频...

Starting new HTTPS connection (1): api.bilibili.com:443

https://api.bilibili.com:443 "POST /x/web-interface/share/add HTTP/1.1" 200 44

分享视频[不要“做”挑战？（十三期下或十四期）]成功🎉🎉

正在进行漫画签到...

Starting new HTTPS connection (1): manga.bilibili.com:443

https://manga.bilibili.com:443 "POST /twirp/activity.v1.Activity/ClockIn HTTP/1.1" 400 94

{'code': 'invalid_argument', 'msg': 'clockin clockin is duplicate', 'meta': {'argument': 'clockin'}}

漫画签到失败,因为重复签到了

正在尝试直播签到...

Starting new HTTPS connection (1): api.live.bilibili.com:443

https://api.live.bilibili.com:443 "GET /sign/doSign HTTP/1.1" 200 86

直播签到失败,因为今日已签到过,无法重复签到

Starting new HTTPS connection (1): qyapi.weixin.qq.com:443

https://qyapi.weixin.qq.com:443 "GET /cgi-bin/gettoken?corpid=wwb0f51ff43128149c&corpsecret=eJxzUup3HCA-FnMWQyMhOT69Ob_jvHLnrJBvkfZBIcY HTTP/1.1" 200 277

Starting new HTTPS connection (1): qyapi.weixin.qq.com:443

https://qyapi.weixin.qq.com:443 "POST /cgi-bin/message/send?access_token=Cuo1q7haXjSsThpa2vGZzIf-FJw1J64MlGPZshyaP-kksTKgpIYW7h9UNWPsWJMzD96rY3nob-RdzMg7TkhIzFFZ3KV99rMa7AO6Gb2lCppgTtEA2YuoUxR_BZg3c9ivLDbuKONNzRfaPeqxdeFAPVmR0FOZihJunJ5cIXGeYP3rPksmnUdDvvFortJbSL99abaXALzqET_aBoq8j_IuHQ HTTP/1.1" 200 124

{'errcode': 0, 'errmsg': 'ok', 'msgid': 'WpLDpQFMGSE843kRbNhgXbcXHkgJnj2JiKed1yJ47e6QFitr0Nx-WLzlKqVwWwsz44VLAzuI1EONGr-ldgfD0Q'}

Starting new HTTP connection (1): api.bilibili.com:80

http://api.bilibili.com:80 "GET /x/space/myinfo HTTP/1.1" 200 None

{'status': True, 'userInfo': {'name': '默认の称昵', 'level': 3, 'coins': 81, 'level_exp': '1710/4500', 'silence': 0}}

等级：lv3<br/>硬币：81<br/>经验：1710/4500<br/>

ERROR RequestId:906e86d5-3720-4e60-aed2-9e8b572fbd4f Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 386, in main\n    return start()\n  File \"/var/user/index.py\", line 266, in start\n    if want_watch[cindex] == '1':\nIndexError: list index out of range","statusCode":430}

END RequestId:906e86d5-3720-4e60-aed2-9e8b572fbd4f

Report RequestId:906e86d5-3720-4e60-aed2-9e8b572fbd4f Duration:6051ms Memory:128MB MemUsage:16.707031MB

**Comment by ICE99125** [comment]
是不是want_watch没有写成1,1的形式，每个账号是否需要观看是独立的

**Comment by Testplayers** [comment]
还是会报错

**Comment by ICE99125** [comment]
修改了一下，看看可行不
